# daemon-tuis/Taskfile.yml
# Unified Build System for R2k Daemon Services
# Dev: github.com/adcondev @ Red2000
# https://taskfile.dev

version: '3'

silent: true

vars:
  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # ๐ GLOBAL CONFIGURATION
  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # Date/Time for ldflags (Windows format)
  DATE:
    sh: powershell -Command "Get-Date -Format 'yyyy-MM-dd'"
  TIME:
    sh: powershell -Command "Get-Date -Format 'HH:mm:ss'"

  INSTALLER_SVC_NAME: "R2k_Installer.exe"

  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # ๐ง LDFLAGS CONFIGURATION
  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # Scale uses internal/config package variables (see SCALE_MODULE)
  SCALE_MODULE: "github.com/adcondev/scale-daemon/internal/config"
  LDFLAGS_SCALE_BASE: "-s -w -X {{.SCALE_MODULE}}.BuildDate={{.DATE}} -X {{.SCALE_MODULE}}.BuildTime={{.TIME}}"

  # Ticket uses internal/daemon package path
  TICKET_MODULE: "github.com/adcondev/ticket-daemon/internal/config"
  LDFLAGS_TICKET_BASE: "-s -w -X {{.TICKET_MODULE}}.BuildDate={{.DATE}} -X {{.TICKET_MODULE}}.BuildTime={{.TIME}}"

  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # ๐ท๏ธ NAMING CONVENTION: R2k_<<Daemon>><<Type>>_<<Env>>.exe
  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # Scale
  SCALE_SVC_ID_LOCAL: "R2k_BasculaServicio_Local"
  SCALE_SVC_ID_REMOTE: "R2k_BasculaServicio_Remote"
  SCALE_CMD_ID_LOCAL: "R2k_BasculaCmd_Local"
  SCALE_CMD_ID_REMOTE: "R2k_BasculaCmd_Remote"
  SCALE_SVC_DISPLAY_LOCAL: "Servicio de Bรกscula (Local)"
  SCALE_SVC_DISPLAY_REMOTE: "Servicio de Bรกscula (Remoto)"
  SCALE_SVC_DESC_REMOTE: "Servicio de comunicaciรณn con bascula via WebSocket"

  # Ticket
  TICKET_SVC_ID_LOCAL: "R2k_TicketServicio_Local"
  TICKET_SVC_ID_REMOTE: "R2k_TicketServicio_Remote"
  TICKET_CMD_ID_LOCAL: "R2k_TicketCmd_Local"
  TICKET_CMD_ID_REMOTE: "R2k_TicketCmd_Remote"
  TICKET_SVC_DISPLAY_LOCAL: "Servicio de Impresiรณn de Tickets (Local)"
  TICKET_SVC_DISPLAY_REMOTE: "Servicio de Impresiรณn de Tickets (Remoto)"
  TICKET_SVC_DESC: "Servicio de impresiรณn de tickets POS via WebSocket"

  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # ๐ฏ INSTALLER CONFIGURATION
  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ

  # Installer paths
  ASSETS_BIN_DIR:
    sh: powershell -Command "(Get-Location).Path + '\internal\assets\bin'"
  DIST_DIR:
    sh: powershell -Command "(Get-Location).Path + '\dist'"

  # Source repositories
  SCALE_SRC: "../scale-daemon"
  TICKET_SRC: "../ticket-daemon"

  # Installer ldflags
  CONFIG_PKG: "github.com/adcondev/poster-tuis/internal/config"
  LDFLAGS_INSTALLER: >-
    -s -w
    -X '{{.CONFIG_PKG}}.BuildDate={{.DATE}}'
    -X '{{.CONFIG_PKG}}.BuildTime={{.TIME}}'
    -X '{{.CONFIG_PKG}}.ScaleIDLocal={{.SCALE_SVC_ID_LOCAL}}'
    -X '{{.CONFIG_PKG}}.ScaleIDRemote={{.SCALE_SVC_ID_REMOTE}}'
    -X '{{.CONFIG_PKG}}.ScaleDisplayLocal={{.SCALE_SVC_DISPLAY_LOCAL}}'
    -X '{{.CONFIG_PKG}}.ScaleDisplayRemote={{.SCALE_SVC_DISPLAY_REMOTE}}'
    -X '{{.CONFIG_PKG}}.TicketIDLocal={{.TICKET_SVC_ID_LOCAL}}'
    -X '{{.CONFIG_PKG}}.TicketIDRemote={{.TICKET_SVC_ID_REMOTE}}'
    -X '{{.CONFIG_PKG}}.TicketDisplayLocal={{.TICKET_SVC_DISPLAY_LOCAL}}'
    -X '{{.CONFIG_PKG}}.TicketDisplayRemote={{.TICKET_SVC_DISPLAY_REMOTE}}'

env:
  CGO_ENABLED: '0'
  GOOS: windows
  GOARCH: amd64

tasks:
  list:
    desc: "๐ List all tasks with descriptions"
    cmds:
      - task --list-all

  init:assets:
    desc: "๐๏ธ Create internal/assets/bin directory"
    internal: true
    cmds:
      - powershell -Command "if (!(Test-Path '{{.ASSETS_BIN_DIR}}')) { New-Item -ItemType Directory -Path '{{.ASSETS_BIN_DIR}}' -Force | Out-Null }"
    status:
      - test -d "{{.ASSETS_BIN_DIR}}"

  init:dist:
    desc: "๐๏ธ Create dist directory"
    internal: true
    cmds:
      - powershell -Command "if (!(Test-Path '{{.DIST_DIR}}')) { New-Item -ItemType Directory -Path '{{.DIST_DIR}}' -Force | Out-Null }"
    status:
      - test -d "{{.DIST_DIR}}"

  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # ๐ฆ INSTALLER SERVICE BUILDS (Output to assets/bin)
  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  installer:build:scale-local:
    desc: "๐ฆ Build Scale Service (Local) for embedding"
    dir: "{{.SCALE_SRC}}"
    deps: [ init:assets ]
    internal: true
    cmds:
      - go build -ldflags "{{.LDFLAGS_SCALE_BASE}} -H=windowsgui -X {{.SCALE_MODULE}}.BuildEnvironment=local -X {{.SCALE_MODULE}}.ServiceName={{.SCALE_SVC_ID_LOCAL}}" -o "{{.ASSETS_BIN_DIR}}/{{.SCALE_SVC_ID_LOCAL}}.exe" ./cmd/BasculaServicio
      - echo "โ Built {{.SCALE_SVC_ID_LOCAL}}.exe for installer"

  installer:build:scale-remote:
    desc: "๐ฆ Build Scale Service (Remoto) for embedding"
    dir: "{{.SCALE_SRC}}"
    deps: [ init:assets ]
    internal: true
    cmds:
      - go build -ldflags "{{.LDFLAGS_SCALE_BASE}} -H=windowsgui -X {{.SCALE_MODULE}}.BuildEnvironment=remote -X {{.SCALE_MODULE}}.ServiceName={{.SCALE_SVC_ID_REMOTE}}" -o "{{.ASSETS_BIN_DIR}}/{{.SCALE_SVC_ID_REMOTE}}.exe" ./cmd/BasculaServicio
      - echo "โ Built {{.SCALE_SVC_ID_REMOTE}}.exe for installer"

  installer:build:ticket-local:
    desc: "๐ฆ Build Ticket Service (Local) for embedding"
    dir: "{{.TICKET_SRC}}"
    deps: [ init:assets ]
    internal: true
    cmds:
      - go build -ldflags "{{.LDFLAGS_TICKET_BASE}} -H=windowsgui -X {{.TICKET_MODULE}}.BuildEnvironment=local" -o "{{.ASSETS_BIN_DIR}}/{{.TICKET_SVC_ID_LOCAL}}.exe" ./cmd/TicketServicio
      - echo "โ Built {{.TICKET_SVC_ID_LOCAL}}.exe for installer"

  installer:build:ticket-remote:
    desc: "๐ฆ Build Ticket Service (Remoto) for embedding"
    dir: "{{.TICKET_SRC}}"
    deps: [ init:assets ]
    internal: true
    cmds:
      - go build -ldflags "{{.LDFLAGS_TICKET_BASE}} -H=windowsgui -X {{.TICKET_MODULE}}.BuildEnvironment=remote" -o "{{.ASSETS_BIN_DIR}}/{{.TICKET_SVC_ID_REMOTE}}.exe" ./cmd/TicketServicio
      - echo "โ Built {{.TICKET_SVC_ID_REMOTE}}.exe for installer"

  installer:build:services:
    desc: "๐ฆ Build ALL service binaries for embedding (4 total)"
    cmds:
      - task: installer:build:scale-local
      - task: installer:build:scale-remote
      - task: installer:build:ticket-local
      - task: installer:build:ticket-remote
      - echo ""
      - echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
      - echo "  โ All service binaries ready for embedding"
      - echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"

  installer:build:
    desc: "๐ Build TUI Installer with embedded services"
    deps: [ installer:build:services, init:dist ]
    cmds:
      - go build -ldflags "{{.LDFLAGS_INSTALLER}}" -o "{{.DIST_DIR}}/{{.INSTALLER_SVC_NAME}}" ./cmd/R2kInstaller
      - echo ""
      - echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
      - echo "  โ INSTALLER BUILD COMPLETE"
      - echo "  ๐ Output:{{.DIST_DIR}}"
      - echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"

  installer:rebuild:
    desc: "๐ Clean and rebuild installer from scratch"
    cmds:
      - task: clean:installer
      - task: installer:build

  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
  # ๐งน UTILITIES
  # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ

  clean:installer:
    desc: "๐งน Clean installer build artifacts"
    internal: true
    cmds:
      - cmd: powershell -Command "if (Test-Path '{{.ASSETS_BIN_DIR}}') { Remove-Item -Recurse -Force '{{.ASSETS_BIN_DIR}}' -ErrorAction SilentlyContinue }"
        platforms: [ windows ]
      - cmd: powershell -Command "if (Test-Path '{{.DIST_DIR}}') { Remove-Item -Recurse -Force '{{.DIST_DIR}}' -ErrorAction SilentlyContinue }"
        platforms: [ windows ]
      - echo "โ Cleaned installer artifacts"

  clean:all:
    desc: "๐งน Clean all project bin and tmp directories"
    internal: true
    cmds:

      - task: clean:installer
      - cmd: powershell -Command "Remove-Item -Path '../scale-daemon/bin', '../scale-daemon/tmp', '../ticket-daemon/bin' -Recurse -Force -ErrorAction SilentlyContinue"
        platforms: [ windows ]
      - cmd: rm -rf ../scale-daemon/bin ../ticket-daemon/bin
        platforms: [ linux, darwin ]
      - echo "โ All projects cleaned"